### ISSUE TITLE
Calling Triangle.dll 64 bit

### ISSUE THREAD

**Issue by marekdam** [wo80/Triangle#7] opened 2016-02-03 15:43 UTC
I compiled the Visual Studio 2013 solution for a 64 bit platform to a DLL and called it from another project using the "tricall.c" example file that comes with Triangle. Running from Release mode works fine however, if I try to run from Debug mode I get a failed assertion after trying to free pointers, 

![capture](https://cloud.githubusercontent.com/assets/13080725/12787304/ded07fa8-ca62-11e5-9025-614e2e5364b3.PNG)

The error occurs after the last call to triangulate().

**Comment by wo80** [comment] 2016-02-03 17:50
I cannot reproduce this. Have you made any changes to the tricall code?
What call exactly causes the exception? Do you have a stacktrace?

One thing that should be fixed for x64:

In triangle.c, line 332, there's `#define VOID int`, so `sizeof(VOID*)` is 4. It should be `#define VOID void`, so `sizeof(VOID*)` is 8.

Does this solve the issue?

**Comment by marekdam** [comment] 2016-02-03 19:33
Ok I have no idea what I was doing wrong and I could not fix my original VS solution to work even with your suggested change, but after copying your provided solution and modifying it to call the built dll it runs fine in Debug/Release. Guess I'm a noob

**Closed as completed** 2016-02-10 21:21 UTC
